#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "naxos" {
	load_video
	set gfxmode=1280x720,800x600,640x480
	multiboot /boot/naxos.bin
}
