name: Build Kernel

on:
  push:
  pull_request:

jobs:
  cross-compiler:
    uses: ./.github/workflows/cross-compiler.yml

  build:
    needs: cross-compiler
    runs-on: ubuntu-latest
    env:
      GCC_VERSION: "14.1.0"
      COMPILER_PATH: ${{ needs.cross-compiler.outputs.compiler-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore cross compiler
        id: cross-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPILER_PATH }}
          key: ${{ runner.os }}-cross-${{ env.GCC_VERSION }}

      - name: Build kernel
        env:
          PATH: "${{ env.COMPILER_PATH }}/bin:${PATH}"
        run: make

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: naxos-bin
          path: naxos.bin
