name: Build Kernel

on:
  pull_request:

jobs:
  cross-compiler:
    uses: ./.github/workflows/cross-compiler.yml

  build:
    needs: cross-compiler
    runs-on: ubuntu-latest
    env:
      GCC_VERSION: "12.2.0"
      BINUTILS_VERSION: "2.40"
      COMPILER_PATH: ${{ github.workspace }}/vendor/cross
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Verify make is available
        run: make --version

      - name: Restore cross compiler
        id: cross-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPILER_PATH }}
          key: cross-compiler-${{ runner.os }}-gcc-${{ env.GCC_VERSION }}-binutils-${{ env.BINUTILS_VERSION }}
          restore-keys: |
            cross-compiler-${{ runner.os }}-gcc-${{ env.GCC_VERSION }}-
            cross-compiler-${{ runner.os }}-

      - name: Setup build environment
        run: |
          echo "Cache hit: ${{ steps.cross-cache.outputs.cache-hit }}"
          if [ -f "${{ env.COMPILER_PATH }}/bin/i686-elf-gcc" ]; then
            echo "✅ Using cached custom cross-compiler"
            ls -la ${{ env.COMPILER_PATH }}/bin/i686*
          else
            echo "⚠️  Custom cross-compiler not found in cache"
            echo "Installing system cross-compiler as fallback..."
            sudo apt-get update
            sudo apt-get install -y gcc-i686-linux-gnu binutils-i686-linux-gnu
            echo "✅ System cross-compiler installed"
          fi

      - name: Build kernel
        env:
          PATH: ${{ env.COMPILER_PATH }}/bin:/usr/local/bin:/usr/bin:/bin
        run: |
          # The Makefile will automatically detect the cross-compiler
          # If vendor/cross/bin/i686-elf-gcc exists, it uses that
          # Otherwise it falls back to system i686-linux-gnu-gcc
          make

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: naxos-bin
          path: naxos.bin

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: naxos.bin
          generate_release_notes: true
