name: Build Kernel

on:
  push:
  pull_request:

jobs:
  cross-compiler:
    uses: ./.github/workflows/cross-compiler.yml

  build:
    needs: cross-compiler
    runs-on: ubuntu-latest
    env:
      GCC_VERSION: "14.1.0"
      BINUTILS_VERSION: "2.44"
      COMPILER_PATH: ${{ needs.cross-compiler.outputs.compiler-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          make --version || { echo "Make was not installed successfully"; exit 1; }
      - name: Restore cross compiler
        id: cross-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPILER_PATH }}
          key: ${{ runner.os }}-cross-${{ env.GCC_VERSION }}-binutils-${{ env.BINUTILS_VERSION }}

      - name: Build kernel
        env:
          PATH: ${{ env.COMPILER_PATH }}/bin:${{ env.PATH }}
        run: make

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: naxos-bin
          path: naxos.bin

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: naxos.bin
          generate_release_notes: true
