name: Build Cross Compiler

on:
  push:
  pull_request:
  workflow_call:
    outputs:
      compiler-path:
        description: "Location of the built cross compiler"
        value: ${{ jobs.build-cross-compiler.outputs.compiler-path }}

jobs:
  build-cross-compiler:
    runs-on: ubuntu-latest
    outputs:
      compiler-path: ${{ steps.set-path.outputs.compiler-path }}
    env:
      GCC_VERSION: "14.1.0"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo wget
          sudo apt-get install --reinstall coreutils
      
      - name: Debug environment
        run: |
          which mkdir
          mkdir --version

      - name: Cache cross compiler
        id: cross-cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vendor/cross
          key: ${{ runner.os }}-cross-${{ env.GCC_VERSION }}-binutils-2.44

      - name: Build cross compiler
        if: steps.cross-cache.outputs.cache-hit != 'true'
        env:
          BINUTILS_VERSION: "2.44"
          GCC_VERSION: "${{ env.GCC_VERSION }}"
          PREFIX: "${{ github.workspace }}/vendor/cross"
          TARGET: "i686-elf"
        run: |
          chmod +x vendor/build_cross_compiler.sh
          vendor/build_cross_compiler.sh

      - name: Set compiler output path
        id: set-path
        run: echo "compiler-path=${{ github.workspace }}/vendor/cross" >> "$GITHUB_OUTPUT"
