name: Build Cross Compiler

on:
  workflow_call:
    outputs:
      compiler-path:
        description: "Location of the built cross compiler"
        value: ${{ jobs.build-cross-compiler.outputs.compiler-path }}
  push:
    tags:
      - '*'

jobs:
  build-cross-compiler:
    runs-on: ubuntu-latest
    outputs:
      compiler-path: ${{ steps.resolve-path.outputs.compiler-path }}
    env:
      GCC_VERSION: "14.1.0"
      BINUTILS_VERSION: "2.44"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo wget
          sudo apt-get install --reinstall coreutils
      
      - name: Debug environment
        run: |
          which mkdir
          mkdir --version

      - name: Check cross compiler in repo
        id: cross-lfs
        run: |
          if [ -x "$GITHUB_WORKSPACE/vendor/cross/bin/i686-elf-gcc" ]; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi


      - name: Build cross compiler
        env:
          BINUTILS_VERSION: "${{ env.BINUTILS_VERSION }}"
          GCC_VERSION: "${{ env.GCC_VERSION }}"
          PREFIX: "${{ github.workspace }}/vendor/cross"
          TARGET: "i686-elf"
        run: |
          chmod +x vendor/build_cross_compiler.sh
          vendor/build_cross_compiler.sh

      #- name: Add cross compiler to repo
       # if: steps.cross-lfs.outputs.found != 'true'
        #run: |
         # git config user.name "github-actions"
          #git config user.email "github-actions@github.com"
          #git add vendor/cross
          #git commit -m "Add prebuilt cross compiler" || echo "nothing to commit"
          #git push

      - name: Package cross compiler
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tar -C vendor -czf cross.tar.gz cross

      - name: Release cross compiler
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: cross.tar.gz
          generate_release_notes: true

      - name: Resolve compiler path
        id: resolve-path
        run: echo "compiler-path=${{ github.workspace }}/vendor/cross" >> "$GITHUB_OUTPUT"
